In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv('C:\\Users\\Administrator\\Downloads\\PropFTX AI2\\price_predictions.csv')

In [3]:
df1

              location  year  quarter    avg_price    max_price    min_price
0         Airport Road  2024  Jan-Mar  6858.920000  8407.298249  5310.541751
1         Airport Road  2024  Apr-Jun  6494.380000  7960.464563  5028.295437
2         Airport Road  2024  Jul-Sep  6384.003333  7825.170733  4942.835934
3         Airport Road  2024  Oct-Dec  6532.067500  8006.659890  5057.475110
4         Airport Road  2025  Jan-Mar  6738.230000  8259.362885  5217.097115
...                ...   ...      ...          ...          ...          ...
6127  oshi Alandi Road  2029  Oct-Dec  7356.800000  8975.527063  5739.356622
6128  oshi Alandi Road  2030  Jan-Mar  7455.830000  9096.346774  5816.614191
6129  oshi Alandi Road  2030  Apr-Jun  7586.380000  9255.621874  5918.461871
6130  oshi Alandi Road  2030  Jul-Sep  7756.660000  9463.368822  6051.304634
6131  oshi Alandi Road  2030  Oct-Dec  7527.625000  9183.938929  5872.624564

[6132 rows x 6 columns]

In [4]:
df2 = pd.read_csv('C:\\Users\\Administrator\\Downloads\\PropFTX AI2\\geocoded_locations.csv')

In [5]:
df2

               Location   Latitude  Longitude
0          Airport Road  23.843144  90.405303
1                Akurdi  18.648642  73.764708
2                Alandi  20.068263  73.697566
3    Alandi Markal Road        NaN        NaN
4           Alandi Road  18.591822  73.874240
..                  ...        ...        ...
227            Wanowrie  18.488368  73.898667
228             Wanwadi  18.957851  76.999161
229               Warje  18.482044  73.800170
230            Yerawada  18.565632  73.886576
231    oshi Alandi Road        NaN        NaN

[232 rows x 3 columns]

In [6]:
import pandas as pd
merged_df = pd.merge(df1, df2, left_on='location', right_on='Location', how='left')
print(merged_df.head())

       location  year  quarter    avg_price    max_price    min_price  \
0  Airport Road  2024  Jan-Mar  6858.920000  8407.298249  5310.541751
1  Airport Road  2024  Apr-Jun  6494.380000  7960.464563  5028.295437
2  Airport Road  2024  Jul-Sep  6384.003333  7825.170733  4942.835934
3  Airport Road  2024  Oct-Dec  6532.067500  8006.659890  5057.475110
4  Airport Road  2025  Jan-Mar  6738.230000  8259.362885  5217.097115

       Location   Latitude  Longitude
0  Airport Road  23.843144  90.405303
1  Airport Road  23.843144  90.405303
2  Airport Road  23.843144  90.405303
3  Airport Road  23.843144  90.405303
4  Airport Road  23.843144  90.405303

In [7]:
merged_df.to_csv('Pune Geo Map Data.csv')