In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('C:\\Users\\Administrator\\Downloads\\PropFTX AI2\\PropFTX AI2\\Maps\\Hyderabad\\Hyderabad Geo Map Data.csv')

In [5]:
df.drop(columns=['Unnamed: 0'],inplace=True)

In [6]:
df

,location,year,quarter,avg_price,max_price,min_price,Location,Latitude,Longitude
0,100 Feet Road,2024,Jan-Mar,7510.855131,9568.276163,5453.345091,100 Feet Road,12.976518,80.219752
1,100 Feet Road,2024,Apr-Jun,7700.319700,9809.640068,5590.908080,100 Feet Road,12.976518,80.219752
2,100 Feet Road,2024,Jul-Sep,8330.239700,10612.111746,6048.268937,100 Feet Road,12.976518,80.219752
3,100 Feet Road,2024,Oct-Dec,8282.896779,10551.800351,6013.895050,100 Feet Road,12.976518,80.219752
4,100 Feet Road,2025,Jan-Mar,7510.855131,9568.276163,5453.345091,100 Feet Road,12.976518,80.219752
...,...,...,...,...,...,...,...,...,...
4839,Yousufguda Main Road,2029,Oct-Dec,6911.763296,8837.785829,4952.284280,Yousufguda Main Road,17.436306,78.429630
4840,Yousufguda Main Road,2030,Jan-Mar,6544.119551,8367.694979,4688.867223,Yousufguda Main Road,17.436306,78.429630
4841,Yousufguda Main Road,2030,Apr-Jun,6614.191161,8457.292648,4739.073592,Yousufguda Main Road,17.436306,78.429630
4842,Yousufguda Main Road,2030,Jul-Sep,6885.765094,8804.543003,4933.656546,Yousufguda Main Road,17.436306,78.429630
4843,Yousufguda Main Road,2030,Oct-Dec,6911.763296,8837.785829,4952.284280,Yousufguda Main Road,17.436306,78.429630

In [7]:
df2 = pd.read_csv('C:\\Users\\Administrator\\Downloads\\PropFTX AI2\\PropFTX AI2\\Maps\\Hyderabad\\Hyderabad_Risk_Factors(Sheet2).csv')

In [8]:
df2

                 Locality      Risk
0           100 Feet Road  Moderate
1            AS Rao Nagar  Moderate
2              Abids Road  Moderate
3                Adibatla  Moderate
4        Alkapur Township  Moderate
..                    ...       ...
177            Uppal Road  Moderate
178      Warangal 0.75way  Moderate
179                Yapral  Moderate
180      Yapral Main Road  Moderate
181  Yousufguda Main Road  Moderate

[182 rows x 2 columns]

In [9]:
merged_df = pd.merge(df, df2, left_on='location', right_on='Locality', how='left')

In [10]:
merged_df.to_csv('Hyderabad Geomap Data.csv')

In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('C:\\Users\\Administrator\\Downloads\\PropFTX AI2\\PropFTX AI2\\Bangalore Property Data.csv')

df['Locality'] = df['Locality'].str.strip().str.lower()
df['Average Price'] = df['Average Price'].str.replace(',', '', regex=False)  
df['Average Price'] = df['Average Price'].replace('-', np.nan)             
df['Average Price'] = pd.to_numeric(df['Average Price'], errors='coerce')   
df = df.dropna(subset=['Average Price'])

start_df = df[df['Quarter'] == 'Jul-Sep 2018'][['Locality', 'Average Price']].copy()
end_df = df[df['Quarter'] == 'Jul-Sep 2024'][['Locality', 'Average Price']].copy()

start_df = start_df.rename(columns={'Average Price': 'Start_Price'})
end_df = end_df.rename(columns={'Average Price': 'End_Price'})

merged = pd.merge(start_df, end_df, on='Locality', how='inner')

merged['Quarterly_Growth'] = ((merged['End_Price'] / merged['Start_Price']) ** (1/24)) - 1
merged['Quarterly Growth (%)'] = (merged['Quarterly_Growth'] * 100).round(4)

merged['CAGR'] = ((merged['End_Price'] / merged['Start_Price']) ** (1/6)) - 1
merged['CAGR (%)'] = (merged['CAGR'] * 100).round(2)

print(merged[['Locality', 'Start_Price', 'End_Price', 'Quarterly Growth (%)', 'CAGR (%)']])
merged.to_csv('Bangalore_quarterly_growth.csv', index=False)

               Locality  Start_Price  End_Price  Quarterly Growth (%)  \
0    100 feet ring road       9300.0    10139.0                0.3605
1        jakkuru layout       5300.0     9448.0                2.4380
2           rajajinagar       9219.0    18416.0                2.9251
3           thanisandra       5163.0    10459.0                2.9851
4             jalahalli       5601.0     7675.0                1.3212
..                  ...          ...        ...                   ...
234       hormavu agara       3200.0     5800.0                2.5089
235              jigani       4583.0     4685.0                0.0918
236       bannerughatta       5989.0    11318.0                2.6874
237        rachenahalli       3612.0    10587.0                4.5826
238      horamavu agara       4488.0     4919.0                0.3828

     CAGR (%)
0        1.45
1       10.11
2       12.22
3       12.49
4        5.39
..        ...
234     10.42
235      0.37
236     11.19
237     19.63
238      1.54

[239 rows x 5 columns]

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('C:\\Users\\Administrator\\Downloads\\PropFTX AI2\\PropFTX AI2\\Bangalore Property Data.csv')

df['Locality'] = df['Locality'].str.strip().str.lower()

df['Average Price'] = df['Average Price'].str.replace(',', '', regex=False)  
df['Average Price'] = df['Average Price'].replace('-', np.nan)             
df['Average Price'] = pd.to_numeric(df['Average Price'], errors='coerce')   

df = df.dropna(subset=['Average Price'])

start_df = df[df['Quarter'] == 'Jul-Sep 2018'][['Locality', 'Average Price']].copy()
end_df = df[df['Quarter'] == 'Jul-Sep 2024'][['Locality', 'Average Price']].copy()

start_df = start_df.rename(columns={'Average Price': 'Start_Price'})
end_df = end_df.rename(columns={'Average Price': 'End_Price'})

merged = pd.merge(start_df, end_df, on='Locality', how='inner')
merged['CAGR'] = ((merged['End_Price'] / merged['Start_Price']) ** (1/6)) - 1
merged['CAGR (%)'] = (merged['CAGR'] * 100).round(2)

print(merged[['Locality', 'Start_Price', 'End_Price', 'CAGR (%)']])
merged.to_csv('Bangalore_cagr_values.csv')

               Locality  Start_Price  End_Price  CAGR (%)
0    100 feet ring road       9300.0    10139.0      1.45
1        jakkuru layout       5300.0     9448.0     10.11
2           rajajinagar       9219.0    18416.0     12.22
3           thanisandra       5163.0    10459.0     12.49
4             jalahalli       5601.0     7675.0      5.39
..                  ...          ...        ...       ...
234       hormavu agara       3200.0     5800.0     10.42
235              jigani       4583.0     4685.0      0.37
236       bannerughatta       5989.0    11318.0     11.19
237        rachenahalli       3612.0    10587.0     19.63
238      horamavu agara       4488.0     4919.0      1.54

[239 rows x 4 columns]

In [21]:
with open('Location_unique.txt', 'w') as f:
    for locality in df['Locality'].unique():
        f.write(f"{locality}\n")