In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv('C:\\Users\\Administrator\\Downloads\\PropFTX AI2\\mumbai_predicted_prices.csv')

In [3]:
df1

,location,quarter,year,min_price,max_price,avg_price
0,90 Feet Road,Jan-Mar,2024.0,13897.805193,23827.414807,18862.610000
1,90 Feet Road,Apr-Jun,2024.0,14018.417913,24034.202087,19026.310000
2,90 Feet Road,Jul-Sep,2024.0,14405.255401,24697.424599,19551.340000
3,90 Feet Road,Oct-Dec,2024.0,14599.075696,25029.724304,19814.400000
4,90 Feet Road,Jan-Mar,2025.0,15476.660335,26534.319665,21005.490000
...,...,...,...,...,...,...
5595,Worli Sea Face,Oct-Dec,2029.0,31507.868287,52618.431713,42063.150000
5596,Worli Sea Face,Jan-Mar,2030.0,36509.281658,60970.838342,48740.060000
5597,Worli Sea Face,Apr-Jun,2030.0,36859.699919,61556.040081,49207.870000
5598,Worli Sea Face,Jul-Sep,2030.0,35331.114707,59003.288626,47167.201667
5599,Worli Sea Face,Oct-Dec,2030.0,34438.869361,57513.230639,45976.050000

In [4]:
df2 = pd.read_csv("C:\\Users\\Administrator\\Downloads\\Mumbai_RecommendationSystem-29 JAN(Sheet5).csv")

In [5]:
df2

                    Locality Final Risk Calculated  Unnamed: 2
0               90 Feet Road         Moderate Risk         NaN
1                 Aarey Road         Moderate Risk         NaN
2    Adi Shankaracharya Marg         Moderate Risk         NaN
3               Agrawal Road             High Risk         NaN
4               Akurli Nagar         Moderate Risk         NaN
..                       ...                   ...         ...
195               Virar West             High Risk         NaN
196                   Wadala         Moderate Risk         NaN
197              Wadala East         Moderate Risk         NaN
198               Walkeshwar              Low Risk         NaN
199           Worli Sea Face              Low Risk         NaN

[200 rows x 3 columns]

In [6]:
import pandas as pd
merged_df = pd.merge(df1, df2, left_on='location', right_on='Locality', how='left')
print(merged_df.head())

       location  quarter    year     min_price     max_price  avg_price  \
0  90 Feet Road  Jan-Mar  2024.0  13897.805193  23827.414807   18862.61
1  90 Feet Road  Apr-Jun  2024.0  14018.417913  24034.202087   19026.31
2  90 Feet Road  Jul-Sep  2024.0  14405.255401  24697.424599   19551.34
3  90 Feet Road  Oct-Dec  2024.0  14599.075696  25029.724304   19814.40
4  90 Feet Road  Jan-Mar  2025.0  15476.660335  26534.319665   21005.49

       Locality Final Risk Calculated  Unnamed: 2
0  90 Feet Road         Moderate Risk         NaN
1  90 Feet Road         Moderate Risk         NaN
2  90 Feet Road         Moderate Risk         NaN
3  90 Feet Road         Moderate Risk         NaN
4  90 Feet Road         Moderate Risk         NaN

In [7]:
merged_df

,location,quarter,year,min_price,max_price,avg_price,Locality,Final Risk Calculated,Unnamed: 2
0,90 Feet Road,Jan-Mar,2024.0,13897.805193,23827.414807,18862.610000,90 Feet Road,Moderate Risk,NaN
1,90 Feet Road,Apr-Jun,2024.0,14018.417913,24034.202087,19026.310000,90 Feet Road,Moderate Risk,NaN
2,90 Feet Road,Jul-Sep,2024.0,14405.255401,24697.424599,19551.340000,90 Feet Road,Moderate Risk,NaN
3,90 Feet Road,Oct-Dec,2024.0,14599.075696,25029.724304,19814.400000,90 Feet Road,Moderate Risk,NaN
4,90 Feet Road,Jan-Mar,2025.0,15476.660335,26534.319665,21005.490000,90 Feet Road,Moderate Risk,NaN
...,...,...,...,...,...,...,...,...,...
5595,Worli Sea Face,Oct-Dec,2029.0,31507.868287,52618.431713,42063.150000,Worli Sea Face,Low Risk,NaN
5596,Worli Sea Face,Jan-Mar,2030.0,36509.281658,60970.838342,48740.060000,Worli Sea Face,Low Risk,NaN
5597,Worli Sea Face,Apr-Jun,2030.0,36859.699919,61556.040081,49207.870000,Worli Sea Face,Low Risk,NaN
5598,Worli Sea Face,Jul-Sep,2030.0,35331.114707,59003.288626,47167.201667,Worli Sea Face,Low Risk,NaN
5599,Worli Sea Face,Oct-Dec,2030.0,34438.869361,57513.230639,45976.050000,Worli Sea Face,Low Risk,NaN

In [8]:
df3 = pd.read_csv('C:\\Users\\Administrator\\Downloads\\geocoded_locations_mumbai(in).csv')

In [9]:
df3

                    Location   Latitude  Longitude
0               90 Feet Road  19.084708  72.915031
1                 Aarey Road  19.166522  72.851003
2    Adi Shankaracharya Marg  19.029205  73.018756
3               Agrawal Road  28.068480  76.111261
4               Akurli Nagar  19.200726  72.859070
..                       ...        ...        ...
195               Virar West  19.453358  72.805797
196                   Wadala  19.026919  72.875934
197              Wadala East  19.021017  72.856896
198               Walkeshwar  18.952420  72.803894
199           Worli Sea Face  19.001408  72.811631

[200 rows x 3 columns]

In [10]:
merged_df.rename(columns={'Final Risk Calculated': 'Risk'},inplace=True)

In [12]:
merged_df.drop(columns=['Unnamed: 2'],inplace=True)

In [14]:
merged_df.drop(columns=['Locality'],inplace=True)

In [15]:
import pandas as pd
merged1_df = pd.merge(merged_df, df3, left_on='location', right_on='Location', how='left')
print(merged1_df.head())

       location  quarter    year     min_price     max_price  avg_price  \
0  90 Feet Road  Jan-Mar  2024.0  13897.805193  23827.414807   18862.61
1  90 Feet Road  Apr-Jun  2024.0  14018.417913  24034.202087   19026.31
2  90 Feet Road  Jul-Sep  2024.0  14405.255401  24697.424599   19551.34
3  90 Feet Road  Oct-Dec  2024.0  14599.075696  25029.724304   19814.40
4  90 Feet Road  Jan-Mar  2025.0  15476.660335  26534.319665   21005.49

            Risk      Location   Latitude  Longitude
0  Moderate Risk  90 Feet Road  19.084708  72.915031
1  Moderate Risk  90 Feet Road  19.084708  72.915031
2  Moderate Risk  90 Feet Road  19.084708  72.915031
3  Moderate Risk  90 Feet Road  19.084708  72.915031
4  Moderate Risk  90 Feet Road  19.084708  72.915031

In [16]:
merged1_df.to_csv('Mumbai Geomap Data.csv')