In [4]:
import pandas as pd

In [5]:
df1 = pd.read_csv('C:\\Users\\Administrator\\Downloads\\PropFTX AI2\\PropFTX AI2\\Hyderabad_recommedation_price_predictions1.csv')

In [6]:
df1

,location,year,quarter,avg_price,max_price,min_price
0,100 Feet Road,2024,Jan-Mar,7510.855131,9568.276163,5453.345091
1,100 Feet Road,2024,Apr-Jun,7700.319700,9809.640068,5590.908080
2,100 Feet Road,2024,Jul-Sep,8330.239700,10612.111746,6048.268937
3,100 Feet Road,2024,Oct-Dec,8282.896779,10551.800351,6013.895050
4,100 Feet Road,2025,Jan-Mar,7510.855131,9568.276163,5453.345091
...,...,...,...,...,...,...
4839,Yousufguda Main Road,2029,Oct-Dec,6911.763296,8837.785829,4952.284280
4840,Yousufguda Main Road,2030,Jan-Mar,6544.119551,8367.694979,4688.867223
4841,Yousufguda Main Road,2030,Apr-Jun,6614.191161,8457.292648,4739.073592
4842,Yousufguda Main Road,2030,Jul-Sep,6885.765094,8804.543003,4933.656546
4843,Yousufguda Main Road,2030,Oct-Dec,6911.763296,8837.785829,4952.284280

In [7]:
df2 = pd.read_csv('C:\\Users\\Administrator\\Downloads\\PropFTX AI2\\PropFTX AI2\\geocoded_locations.csv')

In [8]:
df2

                 Location   Latitude  Longitude
0           100 Feet Road  12.976518  80.219752
1            AS Rao Nagar  17.479869  78.550965
2              Abids Road  17.394234  78.475934
3                Adibatla  17.230899  78.555900
4        Alkapur Township  17.394016  78.371791
..                    ...        ...        ...
177            Uppal Road  17.389823  78.504976
178      Warangal Highway  17.646329  79.051896
179                Yapral  17.503054  78.540798
180      Yapral Main Road        NaN        NaN
181  Yousufguda Main Road  17.436306  78.429630

[182 rows x 3 columns]

In [9]:
import pandas as pd
merged_df = pd.merge(df1, df2, left_on='location', right_on='Location', how='left')
print(merged_df.head())

        location  year  quarter    avg_price     max_price    min_price  \
0  100 Feet Road  2024  Jan-Mar  7510.855131   9568.276163  5453.345091
1  100 Feet Road  2024  Apr-Jun  7700.319700   9809.640068  5590.908080
2  100 Feet Road  2024  Jul-Sep  8330.239700  10612.111746  6048.268937
3  100 Feet Road  2024  Oct-Dec  8282.896779  10551.800351  6013.895050
4  100 Feet Road  2025  Jan-Mar  7510.855131   9568.276163  5453.345091

        Location   Latitude  Longitude
0  100 Feet Road  12.976518  80.219752
1  100 Feet Road  12.976518  80.219752
2  100 Feet Road  12.976518  80.219752
3  100 Feet Road  12.976518  80.219752
4  100 Feet Road  12.976518  80.219752

In [10]:
merged_df.to_csv('Hyderabad Geo Map Data.csv')