In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('C:\\Users\\Administrator\\Downloads\\PropFTX AI2\\PropFTX AI2\\Prediction\\Mumbai\\Mumbai Property Data.csv')

In [5]:
df

,Locality,Quarter,Price Range,Average Price,Q-o-Q,Growth Type,City,Type
0,90 Feet Road,Jul-Sep 2024,"16,266-29,066","22,666",6%,NaN,Mumbai,Residential - Multi Storey Apartment
1,90 Feet Road,Apr-Jun 2024,"15,531-27,163","21,347",1%,NaN,Mumbai,Residential - Multi Storey Apartment
2,90 Feet Road,Jan-Mar 2024,"15,841-27,342","21,591",6%,NaN,Mumbai,Residential - Multi Storey Apartment
3,90 Feet Road,Oct-Dec 2023,"14,887-25,990","20,439",-,NaN,Mumbai,Residential - Multi Storey Apartment
4,90 Feet Road,Jul-Sep 2023,"14,500-25,000","19,750",-1%,NaN,Mumbai,Residential - Multi Storey Apartment
...,...,...,...,...,...,...,...,...
8184,Yari Road,Jul-Sep 2019,"17,375-28,584","22,979",3%,NaN,NaN,NaN
8185,Yari Road,Apr-Jun 2019,"17,412-27,268","22,340",1%,NaN,NaN,NaN
8186,Yari Road,Jan-Mar 2019,"17,696-27,222","22,459",4%,NaN,NaN,NaN
8187,Yari Road,Oct-Dec 2018,"17,718-29,000","23,359",0.30%,NaN,NaN,NaN
8188,Yari Road,Jul-Sep 2018,"17,959-28,602","23,280",7%,NaN,NaN,NaN

In [6]:
df.drop(columns=['Growth Type','City','Type'],inplace=True)

In [7]:
df

          Locality       Quarter    Price Range Average Price  Q-o-Q
0     90 Feet Road  Jul-Sep 2024  16,266-29,066        22,666     6%
1     90 Feet Road  Apr-Jun 2024  15,531-27,163        21,347     1%
2     90 Feet Road  Jan-Mar 2024  15,841-27,342        21,591     6%
3     90 Feet Road  Oct-Dec 2023  14,887-25,990        20,439      -
4     90 Feet Road  Jul-Sep 2023  14,500-25,000        19,750    -1%
...            ...           ...            ...           ...    ...
8184     Yari Road  Jul-Sep 2019  17,375-28,584        22,979     3%
8185     Yari Road  Apr-Jun 2019  17,412-27,268        22,340     1%
8186     Yari Road  Jan-Mar 2019  17,696-27,222        22,459     4%
8187     Yari Road  Oct-Dec 2018  17,718-29,000        23,359  0.30%
8188     Yari Road  Jul-Sep 2018  17,959-28,602        23,280     7%

[8189 rows x 5 columns]

In [8]:
df['Year'] = df['Quarter'].str[-4:]
df['Quarter'] = df['Quarter'].str[:-5]
print(df[['Quarter', 'Year']].head())

   Quarter  Year
0  Jul-Sep  2024
1  Apr-Jun  2024
2  Jan-Mar  2024
3  Oct-Dec  2023
4  Jul-Sep  2023

In [9]:
df

          Locality  Quarter    Price Range Average Price  Q-o-Q  Year
0     90 Feet Road  Jul-Sep  16,266-29,066        22,666     6%  2024
1     90 Feet Road  Apr-Jun  15,531-27,163        21,347     1%  2024
2     90 Feet Road  Jan-Mar  15,841-27,342        21,591     6%  2024
3     90 Feet Road  Oct-Dec  14,887-25,990        20,439      -  2023
4     90 Feet Road  Jul-Sep  14,500-25,000        19,750    -1%  2023
...            ...      ...            ...           ...    ...   ...
8184     Yari Road  Jul-Sep  17,375-28,584        22,979     3%  2019
8185     Yari Road  Apr-Jun  17,412-27,268        22,340     1%  2019
8186     Yari Road  Jan-Mar  17,696-27,222        22,459     4%  2019
8187     Yari Road  Oct-Dec  17,718-29,000        23,359  0.30%  2018
8188     Yari Road  Jul-Sep  17,959-28,602        23,280     7%  2018

[8189 rows x 6 columns]

In [10]:
import pandas as pd
import numpy as np

df = pd.read_csv('C:\\Users\\Administrator\\Downloads\\PropFTX AI2\\PropFTX AI2\\Prediction\\Mumbai\\Mumbai Property Data.csv')

df['Locality'] = df['Locality'].str.strip().str.lower()

df['Average Price'] = df['Average Price'].str.replace(',', '', regex=False)  
df['Average Price'] = df['Average Price'].replace('-', np.nan)             
df['Average Price'] = pd.to_numeric(df['Average Price'], errors='coerce')   

df = df.dropna(subset=['Average Price'])

start_df = df[df['Quarter'] == 'Jul-Sep 2018'][['Locality', 'Average Price']].copy()
end_df = df[df['Quarter'] == 'Jul-Sep 2024'][['Locality', 'Average Price']].copy()

start_df = start_df.rename(columns={'Average Price': 'Start_Price'})
end_df = end_df.rename(columns={'Average Price': 'End_Price'})

merged = pd.merge(start_df, end_df, on='Locality', how='inner')
merged['CAGR'] = ((merged['End_Price'] / merged['Start_Price']) ** (1/6)) - 1
merged['CAGR (%)'] = (merged['CAGR'] * 100).round(2)

print(merged[['Locality', 'Start_Price', 'End_Price', 'CAGR (%)']])
merged.to_csv('Mumbai_cagr_values.csv')

                    Locality  Start_Price  End_Price  CAGR (%)
0               90 feet road      15500.0    22666.0      6.54
1                 aarey road      15600.0    21545.0      5.53
2    adi shankaracharya marg      26700.0    22462.0     -2.84
3                   agripada      30110.0    24323.0     -3.49
4               akurli nagar      13473.0    20989.0      7.67
..                       ...          ...        ...       ...
220               walkeshwar      58646.0    67250.0      2.31
221                    worli      36792.0    50083.0      5.27
222          worli hill road      37524.0    20225.0     -9.79
223           worli sea face      42892.0    57585.0      5.03
224                yari road      23280.0    23586.0      0.22

[225 rows x 4 columns]

In [11]:
negative_cagr_df = merged[merged['CAGR'] < 0]
negative_cagr_df = negative_cagr_df[['Locality', 'Start_Price', 'End_Price', 'CAGR (%)']]
negative_cagr_df.to_csv('Mumbai_negative_cagr_localities.csv', index=False)
print("Saved localities with negative CAGR to 'Mumbai_negative_cagr_localities.csv'")

Saved localities with negative CAGR to 'Mumbai_negative_cagr_localities.csv'