In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv("C:\\Users\\Administrator\\Downloads\\PropFTX AI2\\PropFTX AI2\\Maps\\Bangalore\\Bangalore_Geo_Map_Data.csv")

In [5]:
df1.drop(columns='Unnamed: 0',inplace=True)

In [6]:
df1

,avg_price,location,max_price,min_price,quarter,year,location.1,latitude,longitude
0,9760.2,100 Feet Ring Road,12561.003060,6651.479651,Jan-Mar,2024,100 Feet Ring Road,12.955700,77.601300
1,9844.435,100 Feet Ring Road,12669.410270,6708.884969,Apr-Jun,2024,100 Feet Ring Road,12.955700,77.601300
2,9890.408333,100 Feet Ring Road,12728.576190,6740.215340,Jul-Sep,2024,100 Feet Ring Road,12.955700,77.601300
3,9609.035,100 Feet Ring Road,12366.459500,6548.462200,Oct-Dec,2024,100 Feet Ring Road,12.955700,77.601300
4,9782.413333,100 Feet Ring Road,12589.590770,6666.617817,Jan-Mar,2025,100 Feet Ring Road,12.955700,77.601300
...,...,...,...,...,...,...,...,...,...
6407,4854.24,Horamavu Agara,5988.270292,3647.330151,Oct-Dec,2029,Horamavu Agara,13.037817,77.650462
6408,4540.04,Horamavu Agara,5600.668005,3411.249707,Jan-Mar,2030,Horamavu Agara,13.037817,77.650462
6409,4627.86,Horamavu Agara,5709.004201,3477.235018,Apr-Jun,2030,Horamavu Agara,13.037817,77.650462
6410,4596.25,Horamavu Agara,5670.009585,3453.484213,Jul-Sep,2030,Horamavu Agara,13.037817,77.650462
6411,4799.1125,Horamavu Agara,5920.264101,3605.909003,Oct-Dec,2030,Horamavu Agara,13.037817,77.650462

In [7]:
df2 = pd.read_csv("C:\\Users\\Administrator\\Downloads\\Bangalore Data Final - Copy(Sheet2) (1).csv")

In [8]:
df2

               Locality      Risk
0    100 Feet Ring Road  Moderate
1           Rajajinagar       Low
2           Thanisandra  Moderate
3             Jalahalli  Moderate
4          Channasandra      High
..                  ...       ...
261         Kodigehalli  Moderate
262  Belathur Main Road      High
263       Kasavanahalli  Moderate
264      Vidyaranyapura  Moderate
265      Horamavu Agara  Moderate

[266 rows x 2 columns]

In [9]:
merged_df = pd.merge(df1, df2, left_on='location', right_on='Locality', how='left')

In [13]:
merged_df.drop(columns=['location.1','Locality'],inplace=True)

In [14]:
merged_df

,avg_price,location,max_price,min_price,quarter,year,latitude,longitude,Risk
0,9760.2,100 Feet Ring Road,12561.003060,6651.479651,Jan-Mar,2024,12.955700,77.601300,Moderate
1,9844.435,100 Feet Ring Road,12669.410270,6708.884969,Apr-Jun,2024,12.955700,77.601300,Moderate
2,9890.408333,100 Feet Ring Road,12728.576190,6740.215340,Jul-Sep,2024,12.955700,77.601300,Moderate
3,9609.035,100 Feet Ring Road,12366.459500,6548.462200,Oct-Dec,2024,12.955700,77.601300,Moderate
4,9782.413333,100 Feet Ring Road,12589.590770,6666.617817,Jan-Mar,2025,12.955700,77.601300,Moderate
...,...,...,...,...,...,...,...,...,...
6407,4854.24,Horamavu Agara,5988.270292,3647.330151,Oct-Dec,2029,13.037817,77.650462,Moderate
6408,4540.04,Horamavu Agara,5600.668005,3411.249707,Jan-Mar,2030,13.037817,77.650462,Moderate
6409,4627.86,Horamavu Agara,5709.004201,3477.235018,Apr-Jun,2030,13.037817,77.650462,Moderate
6410,4596.25,Horamavu Agara,5670.009585,3453.484213,Jul-Sep,2030,13.037817,77.650462,Moderate
6411,4799.1125,Horamavu Agara,5920.264101,3605.909003,Oct-Dec,2030,13.037817,77.650462,Moderate

In [15]:
merged_df.to_csv('Bangalore_Geo_Map_Data_Updated.csv')