In [9]:
import pandas as pd

In [10]:
df1 = pd.read_csv('C:\\Users\\Administrator\\Downloads\\PropFTX AI2\\PropFTX AI2\\Maps\\New Delhi\\Delhi_price_predictions.csv')

In [11]:
df1

          location  year  quarter  avg_price     max_price     min_price
0        Alaknanda  2024  Jan-Mar   13229.95  15720.653397  10739.093468
1        Alaknanda  2024  Apr-Jun   13334.58  15844.981302  10824.024352
2        Alaknanda  2024  Jul-Sep   13516.78  16061.482728  10971.920817
3        Alaknanda  2024  Oct-Dec   13687.13  16263.903244  11110.198329
4        Alaknanda  2025  Jan-Mar   14681.17  17445.083695  11917.086372
...            ...   ...      ...        ...           ...           ...
2123  Vipin Garden  2029  Oct-Dec    4340.43   5628.825426   3370.389674
2124  Vipin Garden  2030  Jan-Mar    4643.32   6021.624051   3605.586953
2125  Vipin Garden  2030  Apr-Jun    4679.44   6068.465763   3633.634514
2126  Vipin Garden  2030  Jul-Sep    4775.32   6192.806389   3708.086345
2127  Vipin Garden  2030  Oct-Dec    4795.75   6219.300746   3723.950456

[2128 rows x 6 columns]

In [12]:
df2 = pd.read_csv('C:\\Users\\Administrator\\Downloads\\PropFTX AI2\\PropFTX AI2\\Maps\\New Delhi\\newdelhi_geocoded_locations.csv')

In [13]:
df2

                    Location   Latitude  Longitude
0                  Alaknanda  30.296538  79.156790
1   Alaknanda Don Bosco Road        NaN        NaN
2              Asaf Ali Road  28.644151  77.226827
3                 Chattarpur  28.503846  77.183032
4         Chattarpur Enclave  28.502705  77.184227
..                       ...        ...        ...
75               Vasant Kunj  28.529249  77.154134
76        Vasundhara Enclave  28.601726  77.321121
77                Vikas Marg  28.397880  77.063859
78                 Vikaspuri  28.638643  77.073138
79              Vipin Garden  28.621495  77.025983

[80 rows x 3 columns]

In [14]:
import pandas as pd
merged_df = pd.merge(df1, df2, left_on='location', right_on='Location', how='left')
print(merged_df.head())

    location  year  quarter  avg_price     max_price     min_price   Location  \
0  Alaknanda  2024  Jan-Mar   13229.95  15720.653397  10739.093468  Alaknanda
1  Alaknanda  2024  Apr-Jun   13334.58  15844.981302  10824.024352  Alaknanda
2  Alaknanda  2024  Jul-Sep   13516.78  16061.482728  10971.920817  Alaknanda
3  Alaknanda  2024  Oct-Dec   13687.13  16263.903244  11110.198329  Alaknanda
4  Alaknanda  2025  Jan-Mar   14681.17  17445.083695  11917.086372  Alaknanda

    Latitude  Longitude
0  30.296538   79.15679
1  30.296538   79.15679
2  30.296538   79.15679
3  30.296538   79.15679
4  30.296538   79.15679

In [15]:
merged_df.to_csv('New Delhi Geo Map Data.csv')