In [1]:
import pandas as pd

In [3]:
df1 = pd.read_csv('C:\\Users\\Administrator\\Downloads\\PropFTX AI2\\PropFTX AI2\\Recommendation\\Bangalore\\Bangalore Recommendation Data.csv')

In [4]:
df1

                location predicted_price  quarter  year
0     100 Feet Ring Road          9760.2  Jan-Mar  2024
1     100 Feet Ring Road        9844.435  Apr-Jun  2024
2     100 Feet Ring Road     9890.408333  Jul-Sep  2024
3     100 Feet Ring Road        9609.035  Oct-Dec  2024
4     100 Feet Ring Road     9782.413333  Jan-Mar  2025
...                  ...             ...      ...   ...
6547      Horamavu Agara         4854.24  Oct-Dec  2029
6548      Horamavu Agara         4540.04  Jan-Mar  2030
6549      Horamavu Agara         4627.86  Apr-Jun  2030
6550      Horamavu Agara         4596.25  Jul-Sep  2030
6551      Horamavu Agara       4799.1125  Oct-Dec  2030

[6552 rows x 4 columns]

In [5]:
df2 = pd.read_csv("C:\\Users\\Administrator\\Downloads\\Bangalore Data Final - Copy(Sheet2).csv")

In [6]:
df2

               Locality      Risk
0    100 Feet Ring Road  Moderate
1           Rajajinagar       Low
2           Thanisandra  Moderate
3             Jalahalli  Moderate
4          Channasandra      High
..                  ...       ...
261         Kodigehalli  Moderate
262  Belathur Main Road      High
263       Kasavanahalli  Moderate
264      Vidyaranyapura  Moderate
265      Horamavu Agara  Moderate

[266 rows x 2 columns]

In [7]:
import pandas as pd
merged_df = pd.merge(df1, df2, left_on='location', right_on='Locality', how='left')
print(merged_df.head())

             location predicted_price  quarter  year            Locality  \
0  100 Feet Ring Road          9760.2  Jan-Mar  2024  100 Feet Ring Road
1  100 Feet Ring Road        9844.435  Apr-Jun  2024  100 Feet Ring Road
2  100 Feet Ring Road     9890.408333  Jul-Sep  2024  100 Feet Ring Road
3  100 Feet Ring Road        9609.035  Oct-Dec  2024  100 Feet Ring Road
4  100 Feet Ring Road     9782.413333  Jan-Mar  2025  100 Feet Ring Road

       Risk
0  Moderate
1  Moderate
2  Moderate
3  Moderate
4  Moderate

In [8]:
merged_df.to_csv("Bangalore Recommendation Data1.csv")