In [20]:
import pandas as pd

In [21]:
df = pd.read_csv('C:\\Users\\Administrator\\Downloads\\PropFTX AI2\\Bangalore_recommedation_price_predictions1.csv')

In [22]:
df

,location,year,quarter,avg_price,max_price,min_price
0,100 Feet Ring Road,2024,Jan-Mar,9770.560714,12574.336899,6658.540375
1,100 Feet Ring Road,2024,Apr-Jun,9890.100000,12728.179375,6740.005214
2,100 Feet Ring Road,2024,Jul-Sep,9914.918667,12760.120047,6756.918890
3,100 Feet Ring Road,2024,Oct-Dec,9799.990000,12612.211261,6678.596142
4,100 Feet Ring Road,2025,Jan-Mar,9640.775476,12407.308276,6570.093020
...,...,...,...,...,...,...
5007,Yeswanthpur,2029,Oct-Dec,9360.470000,11488.141722,7232.798278
5008,Yeswanthpur,2030,Jan-Mar,9941.258000,12200.945123,7681.570877
5009,Yeswanthpur,2030,Apr-Jun,9992.338000,12263.635809,7721.040191
5010,Yeswanthpur,2030,Jul-Sep,9999.244444,12272.112115,7726.376774
5011,Yeswanthpur,2030,Oct-Dec,9574.495000,11750.815448,7398.174552

In [23]:
df2 = pd.read_csv('C:\\Users\\Administrator\\Downloads\\PropFTX AI2\\PropFTX AI2\\Economic FactorS Sentiment Analysis.csv')

In [24]:
df2.drop(columns=['Unnamed: 0'],inplace=True)

In [25]:
df2.dropna()

,Locality,Economic Factor,Sentiment Score,Sentiment
0,100 Feet Ring Road,Proximity to key hubs but high property prices...,-0.1901,Negative
1,Rajajinagar,Well-established residential area with strong ...,0.5106,Positive
2,Thanisandra,High growth potential but dependent on complet...,0.2023,Positive
3,Jalahalli,Affordable housing with steady demand and good...,0.3400,Positive
4,Channasandra,Emerging area with limited infrastructure but ...,-0.1154,Negative
...,...,...,...,...
261,Kodigehalli,"High demand and well-connected area, benefitin...",0.2500,Positive
262,Belathur Main Road,"Limited demand, underdeveloped area with gaps ...",-0.3400,Negative
263,Kasavanahalli,Well-established residential locality with dem...,-0.1280,Negative
264,Vidyaranyapura,"Developing area with moderate demand, though l...",0.2732,Positive
265,Horamavu Agara,Growing residential demand with some infrastru...,0.0258,Neutral

In [26]:
merged_df

,location,year,quarter,avg_price,max_price,min_price,Locality,Economic Factor,Sentiment Score,Sentiment
0,100 Feet Ring Road,2024,Jan-Mar,9770.560714,12574.336899,6658.540375,100 Feet Ring Road,Proximity to key hubs but high property prices...,-0.1901,Negative
1,100 Feet Ring Road,2024,Apr-Jun,9890.100000,12728.179375,6740.005214,100 Feet Ring Road,Proximity to key hubs but high property prices...,-0.1901,Negative
2,100 Feet Ring Road,2024,Jul-Sep,9914.918667,12760.120047,6756.918890,100 Feet Ring Road,Proximity to key hubs but high property prices...,-0.1901,Negative
3,100 Feet Ring Road,2024,Oct-Dec,9799.990000,12612.211261,6678.596142,100 Feet Ring Road,Proximity to key hubs but high property prices...,-0.1901,Negative
4,100 Feet Ring Road,2025,Jan-Mar,9640.775476,12407.308276,6570.093020,100 Feet Ring Road,Proximity to key hubs but high property prices...,-0.1901,Negative
...,...,...,...,...,...,...,...,...,...,...
5007,Yeswanthpur,2029,Oct-Dec,9360.470000,11488.141722,7232.798278,Yeswanthpur,Established and growing residential area with ...,0.5994,Positive
5008,Yeswanthpur,2030,Jan-Mar,9941.258000,12200.945123,7681.570877,Yeswanthpur,Established and growing residential area with ...,0.5994,Positive
5009,Yeswanthpur,2030,Apr-Jun,9992.338000,12263.635809,7721.040191,Yeswanthpur,Established and growing residential area with ...,0.5994,Positive
5010,Yeswanthpur,2030,Jul-Sep,9999.244444,12272.112115,7726.376774,Yeswanthpur,Established and growing residential area with ...,0.5994,Positive
5011,Yeswanthpur,2030,Oct-Dec,9574.495000,11750.815448,7398.174552,Yeswanthpur,Established and growing residential area with ...,0.5994,Positive

In [27]:
df4 = pd.read_csv("C:\\Users\\Administrator\\Downloads\\Bangalore Data Final - Copy(Sheet2) (2).csv")

In [28]:
df4

               Locality      Risk
0    100 Feet Ring Road  Moderate
1           Rajajinagar       Low
2           Thanisandra  Moderate
3             Jalahalli  Moderate
4          Channasandra      High
..                  ...       ...
261         Kodigehalli  Moderate
262  Belathur Main Road      High
263       Kasavanahalli  Moderate
264      Vidyaranyapura  Moderate
265      Horamavu Agara  Moderate

[266 rows x 2 columns]

In [29]:
df5 = pd.merge(merged_df,df4)

In [32]:
df5.rename(columns={'avg_price': 'Average Price'}, inplace=True)

In [34]:
df5.rename(columns={'year': 'Year'}, inplace=True)

In [35]:
df5

,location,Year,quarter,Average Price,max_price,min_price,Locality,Economic Factor,Sentiment Score,Sentiment,Risk
0,100 Feet Ring Road,2024,Jan-Mar,9770.560714,12574.336899,6658.540375,100 Feet Ring Road,Proximity to key hubs but high property prices...,-0.1901,Negative,Moderate
1,100 Feet Ring Road,2024,Apr-Jun,9890.100000,12728.179375,6740.005214,100 Feet Ring Road,Proximity to key hubs but high property prices...,-0.1901,Negative,Moderate
2,100 Feet Ring Road,2024,Jul-Sep,9914.918667,12760.120047,6756.918890,100 Feet Ring Road,Proximity to key hubs but high property prices...,-0.1901,Negative,Moderate
3,100 Feet Ring Road,2024,Oct-Dec,9799.990000,12612.211261,6678.596142,100 Feet Ring Road,Proximity to key hubs but high property prices...,-0.1901,Negative,Moderate
4,100 Feet Ring Road,2025,Jan-Mar,9640.775476,12407.308276,6570.093020,100 Feet Ring Road,Proximity to key hubs but high property prices...,-0.1901,Negative,Moderate
...,...,...,...,...,...,...,...,...,...,...,...
4951,Yeswanthpur,2029,Oct-Dec,9360.470000,11488.141722,7232.798278,Yeswanthpur,Established and growing residential area with ...,0.5994,Positive,Moderate
4952,Yeswanthpur,2030,Jan-Mar,9941.258000,12200.945123,7681.570877,Yeswanthpur,Established and growing residential area with ...,0.5994,Positive,Moderate
4953,Yeswanthpur,2030,Apr-Jun,9992.338000,12263.635809,7721.040191,Yeswanthpur,Established and growing residential area with ...,0.5994,Positive,Moderate
4954,Yeswanthpur,2030,Jul-Sep,9999.244444,12272.112115,7726.376774,Yeswanthpur,Established and growing residential area with ...,0.5994,Positive,Moderate
4955,Yeswanthpur,2030,Oct-Dec,9574.495000,11750.815448,7398.174552,Yeswanthpur,Established and growing residential area with ...,0.5994,Positive,Moderate

In [36]:
df5.rename(columns={'quarter': 'Quarter Period'}, inplace=True)

In [38]:
df5.rename(columns={'Economic Factor': 'Economic  Factor'}, inplace=True)

In [40]:
df5.to_csv('12Bangalore_Recommendation_Data.csv')