In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('C:\\Users\\Administrator\\Downloads\\PropFTX AI2\\PropFTX AI2\\Bangalore_re_Data.csv.csv')

In [3]:
df

,Locality,Average Property Age (in years),Vacancy Rate (%),Occupancy Rate (%),Economic Factor,Demand-Supply Ratio,Standard Deviation (?),Risk ( Weighted)
0,100 Feet Ring Road,15,12.0,88.0,Proximity to key hubs but high property prices...,1.2,5.2,NaN
1,Rajajinagar,20,8.0,92.0,Well-established residential area with strong ...,1.3,2.1,NaN
2,Thanisandra,5-10,18.0,82.0,High growth potential but dependent on complet...,0.9,4.5,NaN
3,Jalahalli,15,20.0,80.0,Affordable housing with steady demand and good...,0.8,4.8,NaN
4,Channasandra,10-15,25.0,75.0,Emerging area with limited infrastructure but ...,0.85,7.9,NaN
...,...,...,...,...,...,...,...,...
994,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
997,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.drop(columns=['Average Property Age (in years)','Vacancy Rate (%)','Occupancy Rate (%)','Demand-Supply Ratio','Standard Deviation (?)', 'Risk ( Weighted)'],inplace=True)

In [5]:
df.dropna()

               Locality                                   Economic  Factor
0    100 Feet Ring Road  Proximity to key hubs but high property prices...
1           Rajajinagar  Well-established residential area with strong ...
2           Thanisandra  High growth potential but dependent on complet...
3             Jalahalli  Affordable housing with steady demand and good...
4          Channasandra  Emerging area with limited infrastructure but ...
..                  ...                                                ...
261         Kodigehalli  High demand and well-connected area, benefitin...
262  Belathur Main Road  Limited demand, underdeveloped area with gaps ...
263       Kasavanahalli  Well-established residential locality with dem...
264      Vidyaranyapura  Developing area with moderate demand, though l...
265      Horamavu Agara  Growing residential demand with some infrastru...

[266 rows x 2 columns]

In [6]:
df.columns = df.columns.str.strip()

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 999 entries, 0 to 998
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Locality          266 non-null    object
 1   Economic  Factor  266 non-null    object
dtypes: object(2)
memory usage: 15.7+ KB

In [8]:
sentence = df.iloc[1, df.columns.get_loc('Economic  Factor')]
print(sentence)

Well-established residential area with strong infrastructure and amenities.

In [9]:
import nltk
print(nltk.data.path)

['C:\\Users\\Administrator/nltk_data', 'c:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python313\\nltk_data', 'c:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python313\\share\\nltk_data', 'c:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python313\\lib\\nltk_data', 'C:\\Users\\Administrator\\AppData\\Roaming\\nltk_data', 'C:\\nltk_data', 'D:\\nltk_data', 'E:\\nltk_data']

In [10]:
import os
print(os.getcwd())

c:\Users\Administrator\Downloads\PropFTX AI2\PropFTX AI2

In [11]:
import nltk
nltk.data.path.append('c:\\Users\\Administrator\\Downloads\\PropFTX AI2\\PropFTX AI2')

In [12]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Administrator\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [ ]:
import nltk
import pandas as pd
from nltk.sentiment import SentimentIntensityAnalyzer
nltk.download('vader_lexicon')
sia = SentimentIntensityAnalyzer()
def clean_text(text):
    if not isinstance(text, str):
        return ""
    return text
df['Economic  Factor'] = df['Economic  Factor'].apply(clean_text)
def get_sentiment(text):
    sentiment = sia.polarity_scores(text)
    return sentiment['compound']
df['Sentiment Score'] = df['Economic  Factor'].apply(get_sentiment)
def classify_sentiment(score):
    if score > 0.1:
        return 'Positive'
    elif score < -0.1:
        return 'Negative'
    else:
        return 'Neutral'
df['Sentiment'] = df['Sentiment Score'].apply(classify_sentiment)
print(df)

               Locality                                   Economic  Factor  \
0    100 Feet Ring Road  Proximity to key hubs but high property prices...
1           Rajajinagar  Well-established residential area with strong ...
2           Thanisandra  High growth potential but dependent on complet...
3             Jalahalli  Affordable housing with steady demand and good...
4          Channasandra  Emerging area with limited infrastructure but ...
..                  ...                                                ...
994                 NaN
995                 NaN
996                 NaN
997                 NaN
998                 NaN

     Sentiment Score Sentiment
0            -0.1901  Negative
1             0.5106  Positive
2             0.2023  Positive
3             0.3400  Positive
4            -0.1154  Negative
..               ...       ...
994           0.0000   Neutral
995           0.0000   Neutral
996           0.0000   Neutral
997           0.0000   Neutral
998           0.0000   Neutral

[999 rows x 4 columns]

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\Administrator\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

In [14]:
df.dropna()

,Locality,Economic Factor,Sentiment Score,Sentiment
0,100 Feet Ring Road,Proximity to key hubs but high property prices...,-0.1901,Negative
1,Rajajinagar,Well-established residential area with strong ...,0.5106,Positive
2,Thanisandra,High growth potential but dependent on complet...,0.2023,Positive
3,Jalahalli,Affordable housing with steady demand and good...,0.3400,Positive
4,Channasandra,Emerging area with limited infrastructure but ...,-0.1154,Negative
...,...,...,...,...
261,Kodigehalli,"High demand and well-connected area, benefitin...",0.2500,Positive
262,Belathur Main Road,"Limited demand, underdeveloped area with gaps ...",-0.3400,Negative
263,Kasavanahalli,Well-established residential locality with dem...,-0.1280,Negative
264,Vidyaranyapura,"Developing area with moderate demand, though l...",0.2732,Positive
265,Horamavu Agara,Growing residential demand with some infrastru...,0.0258,Neutral

In [16]:
df.to_csv('Economic FactorS Sentiment Analysis.csv')